"""Agrega fecha a reseñas

Revision ID: 792faa2b6538
Revises: 
Create Date: 2025-05-14 23:27:45.820488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '792faa2b6538'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reseña', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reseña', schema=None) as batch_op:
        batch_op.drop_column('fecha')

    # ### end Alembic commands ###
